[tool.black]
line-length = 100
target-version = ["py312"]
exclude = "(\\.venv/|^data/)"

[tool.mypy]
python_version = "3.12"
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
disallow_untyped_defs = false
no_implicit_optional = true
exclude = "(\\.venv/|^tests/)"

