services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - APP_ENV=dev
      - LOG_LEVEL=INFO
      - LLM_PROVIDER=${LLM_PROVIDER}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - OPENAI_EMBED_MODEL=${OPENAI_EMBED_MODEL}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USERNAME=${NEO4J_USERNAME}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - NEO4J_DATABASE=${NEO4J_DATABASE}
      - AURA_INSTANCEID=${AURA_INSTANCEID}
      - AURA_INSTANCENAME=${AURA_INSTANCENAME}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8000:8000"
    volumes:
      - ..:/app

