services:
  app:
    container_name: agent-swarm-app
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: ["uvicorn", "app.api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    environment:
      - APP_ENV=dev
      - LOG_LEVEL=INFO
      - LLM_PROVIDER=${LLM_PROVIDER}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - OPENAI_EMBED_MODEL=${OPENAI_EMBED_MODEL}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USERNAME=${NEO4J_USERNAME}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - NEO4J_DATABASE=${NEO4J_DATABASE}
      - AURA_INSTANCEID=${AURA_INSTANCEID}
      - AURA_INSTANCENAME=${AURA_INSTANCENAME}
      - DATABASE_URL=${DATABASE_URL}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - LANGSMITH_TRACING=${LANGSMITH_TRACING}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
      - LANGSMITH_PROJECT=${LANGSMITH_PROJECT}
      - LANGSMITH_ENDPOINT=${LANGSMITH_ENDPOINT}
      - LANGCHAIN_ENDPOINT=${LANGCHAIN_ENDPOINT}
      - HANDOFF_THRESHOLD=${HANDOFF_THRESHOLD}
      - RATE_LIMIT_PER_MINUTE=${RATE_LIMIT_PER_MINUTE}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_DEFAULT_CHANNEL=${SLACK_DEFAULT_CHANNEL}
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    depends_on:
      neo4j:
        condition: service_healthy

  neo4j:
    image: neo4j:5.21.0-community
    container_name: agent-swarm-neo4j
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_server_config_strict__validation_enabled=false
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/import
      - neo4j_plugins:/plugins
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p test 'RETURN 1;' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:

